/*
 * File: phi_ddot.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 20-Nov-2025 20:51:12
 */

/* Include Files */
#include "phi_ddot.h"

/* Function Definitions */
/*
 * PHI_DDOT
 *     PHI2 = PHI_DDOT(Tp)
 *
 * Arguments    : double Tp
 * Return Type  : double
 */
double phi_ddot(double Tp)
{
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     2025-11-20 19:35:14 */
  return Tp * 2953.8432454466511;
}

/*
 * File trailer for phi_ddot.c
 *
 * [EOF]
 */
