/*
 * File: theta_ddot.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 20-Nov-2025 20:49:40
 */

/* Include Files */
#include "theta_ddot.h"
#include <math.h>

/* Function Definitions */
/*
 * THETA_DDOT
 *     THETA2 = THETA_DDOT(L0,T,Tp,THETA,THETA1)
 *
 * Arguments    : double L0
 *                double T
 *                double Tp
 *                double theta
 *                double theta1
 * Return Type  : double
 */
double theta_ddot(double L0, double T, double Tp, double theta, double theta1)
{
  double t2;
  double t3;
  double t4;
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     2025-11-20 19:35:14 */
  t2 = cos(theta);
  t3 = sin(theta);
  t4 = L0 * L0;
  return 1.0 /
         ((t2 * t2 * t4 * 1.961363726333745E+42 +
           t3 * t3 * t4 * 1.3550195472288669E+43) +
          4.7915666704630959E+38) *
         (((((T * 1.811039369903676E+24 - Tp * 1.811039369903676E+24) -
             L0 * t3 * 9.1225675140787972E+24) +
            L0 * T * t2 * 4.62970041693687E+25) +
           t2 * t3 * t4 * (theta1 * theta1) * 7.8528978472083187E+23) *
          -1.475739525896764E+19);
}

/*
 * File trailer for theta_ddot.c
 *
 * [EOF]
 */
