/*
 * File: x_ddot.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 20-Nov-2025 19:57:21
 */

/* Include Files */
#include "x_ddot.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  // 处理 NaN
  if (isnan(u0) || isnan(u1)) return NAN;

  // 处理无穷大指数
  if (isinf(u1)) {
    double abs_u0 = fabs(u0);
    if (abs_u0 == 1.0) return 1.0;
    else if (abs_u0 > 1.0) return (u1 > 0.0) ? INFINITY : 0.0;
    else return (u1 > 0.0) ? 0.0 : INFINITY;
  }

  // 处理零指数
  if (u1 == 0.0) return 1.0;

  // 优化常见情况
  if (u1 == 1.0) return u0;
  if (u1 == -1.0) return 1.0 / u0;
  if (u1 == 2.0) return u0 * u0;
  if (u1 == 0.5 && u0 >= 0.0) return sqrt(u0);

  // 负底数的非整数次幂
  if (u0 < 0.0 && u1 != floor(u1)) return NAN;

  // 一般情况
  return pow(u0, u1);
}

/*
 * X_DDOT
 *     X2 = X_DDOT(L0,T,Tp,THETA,THETA1)
 *
 * Arguments    : double L0
 *                double T
 *                double Tp
 *                double theta
 *                double theta1
 * Return Type  : double
 */
double x_ddot(double L0, double T, double Tp, double theta, double theta1)
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double x2_tmp;

  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     2025-11-20 19:35:13 */
  t2 = cos(theta);
  t3 = sin(theta);
  t4 = L0 * L0;
  t5 = rt_powd_snf(L0, 3.0);
  t6 = theta1 * theta1;
  t7 = t2 * t2;
  t8 = t3 * t3;
  x2_tmp = T * t4;
  return ((((((T * 1.653596944829927E+24 +
               rt_powd_snf(t3, 3.0) * t5 * t6 * 7.9318546099989269E+26) +
              L0 * T * t2 * 1.5644683648913071E+27) -
             L0 * Tp * t2 * 1.5644683648913071E+27) +
            L0 * t3 * t6 * 2.8048311378205221E+22) +
           x2_tmp * t7 * 4.6762496226853713E+28) +
          ((x2_tmp * t8 * 4.6762496226853713E+28 -
            t2 * t3 * t4 * 7.880540047630492E+27) +
           t3 * t5 * t6 * t7 * 7.9318546099989269E+26)) *
         1.441151880758559E+16 /
         ((t4 * t7 * 1.961363726333745E+42 + t4 * t8 * 1.3550195472288669E+43) +
          4.7915666704630959E+38);
}

/*
 * File trailer for x_ddot.c
 *
 * [EOF]
 */
